services:
  python:
    build:
      dockerfile: ./docker/python.Dockerfile
      args:
        REPO_NAME: git-hooks
  bash:
    build:
      dockerfile: ./docker/bash.Dockerfile
  markdown:
    build:
      dockerfile: ./docker/markdown.Dockerfile
