#!/usr/bin/env bash

# shellcheck disable=SC1091
source "${0%/*}/ci.sh"

get_git_branch() {
    git branch --show-current
}

reject_commit_main_branch() {
    local current_branch="$1"

    if [[ "$current_branch" == 'main' ]]; then
        echo 'Cannot commit to main branch.'
        exit 1
    fi
}

main() {
    set -o errexit
    set -o pipefail
    reject_commit_main_branch "$(get_git_branch)"
    run_ci_bash_shfmt
}

main
